name: pygobject-app-snap-template # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pygobject-app-snap-template:
    command: desktop-launch $SNAP/app
    plugs: [unity7, x11, opengl, gsettings]

parts:
  app:
    plugin: dump
    source: ./src
    organize:
      main.py: app

    stage-packages:
      - python3
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - libcanberra-gtk-module
    after: [desktop-gtk3]
